ConvBlock:
    in_channels: 1
    out_channels: 128
    kernel_size: 5
FeedForwardBlock:
    in_features: 327168
    hidden_dim: 128
    out_features: 1
    dropout: 0.2
GlycN:
    lr: 0.00001
    epochs: 25
    batch_size: 32