ConvBlock:
    in_channels: 1
    out_channels: 64
    kernel_size: 3
FeedForwardBlock:
    in_features: 163840
    hidden_dim: 64
    out_features: 1
    dropout: 0.2
GlycN:
    lr: 0.001
    epochs: 100
    batch_size: 64