ConvBlock:
    in_channels: 1
    out_channels: 16
    kernel_size: 3
    pool_kernel: 2
FeedForwardBlock:
    in_features: 20480
    hidden_dim: 64
    out_features: 2
    dropout: 0.2
GlycN:
    lr: 0.002
    epochs: 10
    batch_size: 128